version: '3.8'

services:
  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: noticias-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_ORIGINS=http://localhost:5173,http://172.17.200.87:5173,http://localhost:3000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - noticias-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: noticias-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    command: npm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - noticias-network
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mi_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave
    ports:
      - "5432:5432"
    networks:
      - noticias-network

networks:
  noticias-network:
    driver: bridge