"""crear tabla estilo_item

Revision ID: crear_tabla_estilo_item
Revises: 
Create Date: 2025-10-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'crear_tabla_estilo_item'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estilo_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('estilo_id', sa.Integer(), nullable=False),
        sa.Column('nombre_archivo', sa.String(length=200), nullable=False),
        sa.Column('contenido', sa.Text(), nullable=True),
        sa.Column('orden', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['estilo_id'], ['estilo_maestro.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estilo_item_estilo_id'), 'estilo_item', ['estilo_id'], unique=False)
    op.create_index(op.f('ix_estilo_item_id'), 'estilo_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estilo_item_id'), table_name='estilo_item')
    op.drop_index(op.f('ix_estilo_item_estilo_id'), table_name='estilo_item')
    op.drop_table('estilo_item')
    # ### end Alembic commands ###